[simulation]
gui = false
max_steps = 3600
n_cars_generated = 2600
n_peds_generated = 1000
episode_seed = 5000
yellow_duration = 4
green_duration = 8
scenario = 5

[agent]
n_agents = 4
num_states = 181
num_actions = 9

#Escolha de arquitetura das redes neuronais
#Alterar entre DQN ou MAPPO, descomentar o desejado
[network]
#algorithm = MAPPO
algorithm = DQN

[dir]
models_path_name = models
sumocfg_file_name = sumo_config.sumocfg
model_to_test = 1