[simulation]
gui = False
total_episodes = 200
max_steps = 3600
n_cars_generated = 4204
n_peds_generated = 1000
yellow_duration = 4
scenario = 6

[model]
num_layers = 2
width_layers = 256
batch_size = 128
learning_rate = 0.0001
training_epochs = 50

[memory]
memory_size_min = 600
memory_size_max = 100000

[agent]
; Cell_1 (J1/J3): 84 base + 9 action_encode = 93
; Cell_2 (J2/J4): 124 base + 9 action_encode = 135
num_states_cell1    = 93
num_states_cell2    = 133
;num_states_duration = 170           ; mantido mas não usado
num_actions_phase    = 2
num_actions_duration = 4
gamma = 0.75

[dir]
models_path_name = models
sumocfg_file_name = sumo_config.sumocfg